SYSTEM:
  MODELNAME: "SCRATCH"
  SAVEFOLDER: "/Shelburne/Results/Scratch/Single_1_Anti_2_Dense_1024_Ensemble"
  
SHELDATA:
  ThreeSets: "/Shelburne/Data/Train/TLPARP/shelburne_3sets.pkl"
  Info: "/Shelburne/Data/Train/TLPARP/shelburne_info.csv"

ScratchTrain:
  BATCH_SIZE: 32
  EPOCHS: 100
